package discgo

import (
	"time"

	"encoding/json"

	"net/url"
	"strconv"

	"bytes"
	"io"
	"mime/multipart"
)

// Channel represents a channel in Discord.
// If IsPrivate is set this is a DM Channel otherwise this is a Guild Channel.
// Guild Channel represents an isolated set of users and messages within a Guild.
// DM Channel represent a one-to-one conversation between two users, outside of the
// scope of guilds.
// TODO I really don't like this merger, surely there must be a better way? perhaps an interface? it would make the endpoint API a lot more unclean though. gotta think
type Channel struct {
	ID                   string       `json:"id"`
	GuildID              string       `json:"guild_id"`
	Name                 string       `json:"name"`
	Type                 string       `json:"type"`
	Position             int          `json:"position"`
	IsPrivate            bool         `json:"is_private"`
	PermissionOverwrites []*Overwrite `json:"permission_overwrites"`
	Topic                string       `json:"topic"`
	Recipient            *User        `json:"recipient"`
	LastMessageID        string       `json:"last_message_id"`
	Bitrate              int          `json:"bitrate"`
	UserLimit            int          `json:"user_limit"`
}

// Message represents a message sent in a channel within Discord.
// The author object follows the structure of the user object, but
// is only a valid user in the case where the message is generated
// by a user or bot user. If the message is generated by a webhook,
// the author object corresponds to the webhook's id, username, and avatar.
// You can tell if a message is generated by a webhook by checking for the
// webhook_id on the message object.
type Message struct {
	ID              string        `json:"id"`
	ChannelID       string        `json:"channel_id"`
	Author          *User         `json:"author"`
	Content         string        `json:"content"`
	Timestamp       *time.Time    `json:"timestamp"`
	EditedTimestamp *time.Time    `json:"edited_timestamp"`
	TTS             bool          `json:"tts"`
	MentionEveryone bool          `json:"mention_everyone"`
	Mentions        []*User       `json:"mentions"`
	MentionRoles    []string      `json:"mention_roles"`
	Attachments     []*Attachment `json:"attachments"`
	Embeds          []*Embed      `json:"embeds"`
	Reactions       []*Reaction   `json:"reactions"`
	Nonce           string        `json:"nonce"`
	Pinned          bool          `json:"pinned"`
	WebhookID       string        `json:"webhook_id"`
}

type Reaction struct {
	Count int
	Me    bool
	Emoji *ReactionEmoji
}

type ReactionEmoji struct {
	ID   *string // nullable
	Name string
}

type Overwrite struct {
	ID    string
	Type  string
	Allow int
	Deny  int
}

type Embed struct {
	Title       string          `json:"title,omitempty"`
	Type        string          `json:"type,omitempty"`
	Description string          `json:"description,omitempty"`
	URL         string          `json:"url,omitempty"`
	Timestamp   *time.Time      `json:"timestamp,omitempty"`
	Color       int             `json:"color,omitempty"`
	Footer      *EmbedFooter    `json:"footer,omitempty"`
	Image       *EmbedImage     `json:"image,omitempty"`
	Thumbnail   *EmbedThumbnail `json:"thumbnail,omitempty"`
	Video       *EmbedVideo     `json:"video,omitempty"`
	Provider    *EmbedProvider  `json:"provider,omitempty"`
	Author      *EmbedAuthor    `json:"author,omitempty"`
	Fields      []*EmbedField   `json:"fields,omitempty"`
}

type EmbedThumbnail struct {
	URL      string `json:"url,omitempty"`
	ProxyURL string `json:"proxy_url,omitempty"`
	Height   int    `json:"height,omitempty"`
	Width    int    `json:"width,omitempty"`
}

type EmbedVideo struct {
	URL    string `json:"url,omitempty"`
	Height int    `json:"height,omitempty"`
	Width  int    `json:"width,omitempty"`
}

type EmbedImage struct {
	URL      string `json:"url,omitempty"`
	ProxyURL string `json:"proxy_url,omitempty"`
	Height   int    `json:"height,omitempty"`
	Width    int    `json:"width,omitempty"`
}

type EmbedProvider struct {
	Name string `json:"name,omitempty"`
	URL  string `json:"url,omitempty"`
}

type EmbedAuthor struct {
	Name         string `json:"name,omitempty"`
	URL          string `json:"url,omitempty"`
	IconURL      string `json:"icon_url,omitempty"`
	ProxyIconURL string `json:"proxy_icon_url,omitempty"`
}

type EmbedFooter struct {
	Text         string `json:"text,omitempty"`
	IconURL      string `json:"icon_url,omitempty"`
	ProxyIconURL string `json:"proxy_icon_url,omitempty"`
}

type EmbedField struct {
	Name   string `json:"name,omitempty"`
	Value  string `json:"value,omitempty"`
	Inline bool   `json:"inline,omitempty"`
}

type Attachment struct {
	ID       string `json:"id,omitempty"`
	Filename string `json:"filename,omitempty"`
	Size     int    `json:"size,omitempty"`
	URL      string `json:"url,omitempty"`
	ProxyURL string `json:"proxy_url,omitempty"`
	Height   int    `json:"height,omitempty"`
	Width    int    `json:"width,omitempty"`
}

// TODO create mention method on User, Channel, Role and Custom ReactionEmoji structs
// https://discordapp.com/developers/docs/resources/channel#message-formatting

type ChannelEndpoint struct {
	*endpoint
}

func (c *Client) Channel(cID string) *ChannelEndpoint {
	e2 := c.e.appendMajor("channels").appendMajor(cID)
	return &ChannelEndpoint{e2}
}

func (e *ChannelEndpoint) Get() (ch *Channel, err error) {
	return ch, e.doMethod("GET", nil, &ch)
}

type ChannelModifyParams struct {
	Name      string `json:"name,omitempty"`
	Position  int    `json:"position,omitempty"`
	Topic     string `json:"topic,omitempty"`
	Bitrate   int    `json:"bitrate,omitempty"`
	UserLimit int    `json:"user_limit,omitempty"`
}

func (e *ChannelEndpoint) Modify(params *ChannelModifyParams) (ch *Channel, err error) {
	return ch, e.doMethod("PATCH", params, &ch)
}

func (e *ChannelEndpoint) Delete() (ch *Channel, err error) {
	return ch, e.doMethod("DELETE", nil, &ch)
}

type MessagesEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Messages() *MessagesEndpoint {
	return &MessagesEndpoint{e.appendMajor("messages")}
}

type MessagesGetParams struct {
	AroundID string
	BeforeID string
	AfterID  string
	Limit    int
}

func (params *MessagesGetParams) rawQuery() string {
	v := make(url.Values)
	if params.AroundID != "" {
		v.Set("around", params.AroundID)
	}
	if params.BeforeID != "" {
		v.Set("before", params.BeforeID)
	}
	if params.AfterID != "" {
		v.Set("after", params.AfterID)
	}
	if params.Limit > 0 {
		v.Set("limit", strconv.Itoa(params.Limit))
	}
	return v.Encode()
}

func (e *MessagesEndpoint) Get(params *MessagesGetParams) (messages []*Message, err error) {
	req := e.newRequest("GET", nil)
	if params != nil {
		req.URL.RawQuery = params.rawQuery()
	}
	return messages, e.do(req, &messages)
}

type MessagesCreateParams struct {
	Content string `json:"content,omitempty"`
	Nonce   string `json:"nonce,omitempty"`
	TTS     bool   `json:"tts,omitempty"`
	File    *File  `json:"-"`
	Embed   *Embed `json:"embed,omitempty"`
}

type File struct {
	Name    string
	Content io.Reader
}

func (e *MessagesEndpoint) Create(params *MessagesCreateParams) (m *Message, err error) {
	reqBody := &bytes.Buffer{}
	reqBodyWriter := multipart.NewWriter(reqBody)

	payloadJSON, err := json.Marshal(params)
	if err != nil {
		return nil, err
	}
	w, err := reqBodyWriter.CreateFormField("payload_json")
	if err != nil {
		return nil, err
	}
	_, err = w.Write(payloadJSON)
	if err != nil {
		return nil, err
	}

	if params.File != nil {
		w, err := reqBodyWriter.CreateFormFile("file", params.File.Name)
		if err != nil {
			return nil, err
		}

		_, err = io.Copy(w, params.File.Content)
		if err != nil {
			return nil, err
		}
	}

	err = reqBodyWriter.Close()
	if err != nil {
		return nil, err
	}

	req := e.newRequest("POST", reqBody)
	req.Header.Set("Content-Type", reqBodyWriter.FormDataContentType())
	return m, e.do(req, &m)
}

type MessageEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Message(mID string) *MessageEndpoint {
	e2 := e.Messages().appendMinor(mID)
	return &MessageEndpoint{e2}
}

func (e *MessageEndpoint) Get() (m *Message, err error) {
	return m, e.doMethod("GET", nil, &m)
}

type MessageEditParams struct {
	Content string `json:"content,omitempty"`
	Embed   *Embed `json:"embed,omitempty"`
}

func (e *MessageEndpoint) Patch(params *MessageEditParams) (m *Message, err error) {
	return m, e.doMethod("PATCH", params, &m)
}

func (e *MessageEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}

type ReactionsEndpoint struct {
	*endpoint
}

func (e *MessageEndpoint) Reactions() *ReactionsEndpoint {
	return &ReactionsEndpoint{e.appendMajor("reactions")}
}

func (e *ReactionsEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}

type EmojiReactionsEndpoint struct {
	*endpoint
}

func (e *MessageEndpoint) Emoji(emoji string) *EmojiReactionsEndpoint {
	e2 := e.appendMinor(emoji)
	return &EmojiReactionsEndpoint{e2}
}

func (e *EmojiReactionsEndpoint) Get() (users []*User, err error) {
	return users, e.doMethod("GET", nil, &users)
}

type ReactionEndpoint struct {
	*endpoint
}

func (e *EmojiReactionsEndpoint) User(uID string) *ReactionEndpoint {
	e2 := e.appendMinor(uID)
	return &ReactionEndpoint{e2}
}

func (e *ReactionEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}

func (e *EmojiReactionsEndpoint) Create() error {
	e2 := e.appendMinor("@me")
	return e2.doMethod("PUT", nil, nil)
}

type BulkDeleteEndpoint struct {
	*endpoint
}

func (e *MessagesEndpoint) BulkDelete() *BulkDeleteEndpoint {
	e2 := e.appendMajor("bulk-delete")
	return &BulkDeleteEndpoint{e2}
}

func (e *BulkDeleteEndpoint) Do(messageIDs []string) error {
	return e.doMethod("POST", messageIDs, nil)
}

type PermissionOverwriteEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) PermissionOverwrite(overwriteID string) *PermissionOverwriteEndpoint {
	e2 := e.appendMajor("permissions").appendMinor(overwriteID)
	return &PermissionOverwriteEndpoint{e2}
}

type PermissionOverwriteEditParams struct {
	Allow int    `json:"allow"`
	Deny  int    `json:"deny"`
	Type  string `json:"type"`
}

func (e *PermissionOverwriteEndpoint) Edit(params *PermissionOverwriteEditParams) error {
	return e.doMethod("PUT", params, nil)
}

func (e *PermissionOverwriteEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}

type InvitesEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Invites() *InvitesEndpoint {
	e2 := e.appendMajor("invites")
	return &InvitesEndpoint{e2}
}

func (e *InvitesEndpoint) Get() (invites []*Invite, err error) {
	return invites, e.doMethod("GET", nil, &invites)
}

type InviteCreateParams struct {
	MaxAge    int  `json:"max_age,omitempty"`
	MaxUses   int  `json:"max_uses,omitempty"`
	Temporary bool `json:"temporary,omitempty"`
	Unique    bool `json:"unique,omitempty"`
}

func (e *InvitesEndpoint) Create(params *InviteCreateParams) (invite *Invite, err error) {
	return invite, e.doMethod("POST", params, &invite)
}

type TypingIndicatorEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) TypingIndicator() *TypingIndicatorEndpoint {
	e2 := e.appendMajor("typing")
	return &TypingIndicatorEndpoint{e2}
}

func (e *TypingIndicatorEndpoint) Trigger() error {
	return e.doMethod("POST", nil, nil)
}

type PinsEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Pins() *PinsEndpoint {
	e2 := e.appendMajor("pins")
	return &PinsEndpoint{e2}
}

func (e *PinsEndpoint) Get() (messages []*Message, err error) {
	return messages, e.doMethod("GET", nil, &messages)
}

type PinEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Pin(mID string) *PinEndpoint {
	e2 := e.Pins().appendMinor(mID)
	return &PinEndpoint{e2}
}

func (e *PinEndpoint) Add() error {
	return e.doMethod("PUT", nil, nil)
}

func (e *PinEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}

type RecipientEndpoint struct {
	*endpoint
}

func (e *ChannelEndpoint) Recipient(uID string) *RecipientEndpoint {
	e2 := e.appendMajor("recipients").appendMinor(uID)
	return &RecipientEndpoint{e2}
}

func (e *RecipientEndpoint) Add() error {
	return e.doMethod("PUT", nil, nil)
}

func (e *RecipientEndpoint) Delete() error {
	return e.doMethod("DELETE", nil, nil)
}
